version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: junglecoders/ruby24-primary:0.0.2
        environment:
          HEADLESS: 1
          BUNDLE_PATH: ~/.bundle
      - image: postgres:9.5
        environment:
          POSTGRES_USER: app
    steps:
      - checkout

      - run: gem install rails

      - restore_cache:
          key: bundle-v1.0

      - run: cd ~/ && rails new testapp -m code/template.rb -d postgresql --skip-turbolinks

      - run: cd ~/testapp && NO_TENANT=1 bundle exec rake assets:precompile && bundle exec rspec

      - save_cache:
          key: bundle-v1.0
          paths:
            - ~/.bundle

      # Store Capybara screenshots. Super helpful if tests failed
      - store_artifacts:
          path: ~/testapp/tmp/capybara

      # Store SimpleCov output
      - store_artifacts:
          path: ~/testapp/coverage
